name: wallet_utils
description: A dart ravencoin transaction signing library.
version: 3.0.16
homepage: https://github.com/moontreeapp/wallet_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bech32: ^0.2.1
  bip32: ^2.0.0
  bip39: ^1.0.6
  bs58check: ^1.0.2
  bs58: ^1.0.2
  collection: ^1.16.0
  hex: ^0.2.0
  meta: ^1.8.0
  pointycastle: ^3.6.2
  convert: ^3.0.2
  tuple: ^2.0.1

dev_dependencies:
  test: ^1.17.5
